<?php
define('STATE_NEW', 0);
define('STATE_EXPECT_ACTION', 1);
define('STATE_EXPECT_NAME', 2);
define('STATE_EXPECT_DESCRIPTION', 3);
define('STATE_EXPECT_LOCATION', 4);
define('STATE_EXPECT_QUANTITY', 5);
define('STATE_EXPECT_PRICE', 6);

define('STATE_EXPECT_ITEM_ID_REMOVE', 7);
define('STATE_EXPECT_REMOVE_CONFIRMATION', 8);

define('ACTION_UPLOAD', 1);
define('ACTION_REMOVE', 2);
define('ACTION_VIEW_PRODUCT_DETAILS', 3);


define('TIMEOUT', 10);

?>